global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    instance: 'dclocal-prometheus2'
    cluster: 'dclocal-prometheus2'
    replica: '1'

scrape_configs:
  - job_name: dclocal-prometheus2
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 'localhost:9090'
        labels:
          instance: 'dclocal-prometheus2'
          target: prometheus

  - job_name: thanos-store
    scrape_interval: 5s
    static_configs:
    - targets:
      - 'thanos-store:10902'
      labels:
        instance: 'dclocal-prometheus2'
        target: thanos-store

  - job_name: thanos-receive
    scrape_interval: 5s
    static_configs:
    - targets:
      - 'thanos-receive:10902'
      labels:
        instance: 'dclocal-prometheus2'
        target: thanos-receive

  - job_name: thanos-ruler
    scrape_interval: 5s
    static_configs:
    - targets:
      - 'thanos-ruler:10902'
      labels:
        instance: 'dclocal-prometheus2'
        target: thanos-ruler

  - job_name: thanos-querier
    scrape_interval: 5s
    static_configs:
    - targets:
      - 'thanos-querier:10902'
      labels:
        instance: 'dclocal-prometheus2'
        target: thanos-querier

  - job_name: thanos-bucket-web
    scrape_interval: 5s
    static_configs:
    - targets:
      - 'thanos-bucket-web:10902'
      labels:
        instance: 'dclocal-prometheus2'
        target: thanos-bucket-web

  - job_name: thanos-compactor
    scrape_interval: 5s
    static_configs:
    - targets:
      - 'thanos-compactor:10902'
      labels:
        instance: 'dclocal-prometheus2'
        target: thanos-compactor

remote_write:
  - url: "http://thanos-receive:10903/api/v1/receive"
