global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    cluster: 'beacon-prometheus2'
    
scrape_configs:
  - job_name: beacon-prometheus2
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 'localhost:9090'
        labels:
          instance: 'prometheus'
    file_sd_configs:
      - files:
          - "/etc/prometheus/file_sd/*.yml"

remote_write:
  - url: "http://dclocal-prometheus1:9090/api/v1/write"
