global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    instance: 'beacon-prometheus4'
    cluster: 'beacon-prometheus4'
    replica: '1'
    
scrape_configs:
  - job_name: beacon-prometheus4
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 'localhost:9090'
        labels:
          instance: 'beacon-prometheus1'
          target: prometheus
    file_sd_configs:
      - files:
          - "/etc/prometheus/file_sd/*.yml"

remote_write:
  - url: "http://dclocal-prometheus2:9090/api/v1/write"
