global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    cluster: 'dclocal-prometheus1'

scrape_configs:
  - job_name: dclocal-prometheus1
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 'localhost:9090'
        labels:
          instance: 'prometheus'

      - targets:
        - 'thanos-store:10902'
        labels:
          instance: thanos-store

      - targets:
        - 'thanos-receive:10902'
        labels:
          instance: thanos-receive

      - targets:
        - 'thanos-ruler:10902'
        labels:
          instance: thanos-ruler

      - targets:
        - 'thanos-querier:10902'
        labels:
          instance: thanos-querier

      - targets:
        - 'thanos-bucket-web:10902'
        labels:
          instance: thanos-bucket-web

      - targets:
        - 'thanos-compactor:10902'
        labels:
          instance: thanos-compactor

remote_write:
  - url: "http://thanos-receive:10903/api/v1/receive"
